version: '3.0'
services:
  web:
    build: .
    ports:
    - "8080:3000"
    links:
    - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'scrum_master'
      MYSQL_ROOT_PASSWORD: 'password'
