version: '3.0'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'scrum-master'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
    - scrum_master_volume:/var/lib/mysql
    container_name: scrum_bot_db

  web:
    build: .
    ports:
    - "9871:8080"
    container_name: scrum_bot_web
    links:
    - db

  migration:
    build:
      context : "."
    command: ["./wait-for-it/wait-for-it.sh", "db:3306", "--timeout=120", "--", "npm", "run", "migrate"]
    container_name: scrum_bot_migration

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      PMA_HOST : 'db'
    ports:
    - "9872:80"
    container_name: scrum_bot_phpmyadmin
    links:
    - db

volumes:
  scrum_master_volume:
